---
title: "Gov 50 Final Project"
author: "Lydia Fraser"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to Chinatown-preferably Boston's Chinatown but am also open to doing research into one based in another city. I would also be interested in doing research on a suburban Asian enclave in the greater Los Angeles area of Southern California.

```{r}
knitr::opts_chunk$set(error = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
housing <- read_csv("housing_data.csv")
```

## Project Proposal
My research question would be related to the connection between housing affordability in Boston's Chinatown and looking at a certain factor (that I will hopefully determine after a deeper analysis of my topic) to see its relationship to housing prices in Boston's Chinatown. 
It is the Housing Affordability Data System which categorizes housing units by affordability and households by income to allow analysts to observe affordability measures. I will filter the data to the specific area of Boston I want to look at. I want to use this data to more closely investigate the impact of gentrification and the driving factors of rising housing prices in Chinatown. 
I hypothesize that there will be some correlation between the timelines of the construction of infrastructure like the Tufts Medical Center and decrease in housing affordability in Chinatown. 

## Milestone 3
** I have loaded my data, but I am having issues figuring out how to reformat the data so that there are more than one column (right now, all of the columns are combined into one). I will seek help to resolve this issue, and once it is resolved, my data visualization should have no issues. 


burden_plot <- ggplot(housing, mapping = aes(x = burden)) + geom_bar()
burden_plot
